/**
 * 토큰 생성기 (03 문서 §1) — `src/tokens/*.ts`가 유일한 진실의 원천이고,
 * 아래 두 파일은 전부 이 스크립트의 생성물이다:
 *
 *   1. packages/ui/src/styles/tokens.css     — :root semantic 변수 + [data-theme="dark"] 재정의
 *   2. packages/ui/src/styles/tailwind-preset.css — Tailwind v4 @theme 매핑 (semantic 네임만)
 *
 * 생성물은 커밋한다 — CI가 재생성 후 diff를 검사해 드리프트를 차단한다(validate-tokens).
 * 문서 사이트 팔레트는 별도 생성물 없이 `@jeon-ji/common-ui/tokens`를 직접 import 한다
 * (workspace 참조라 소스와 어긋날 수 없다).
 *
 * 사용법:  tsx scripts/build-tokens.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { semanticColor, type ThemedColor } from "../packages/ui/src/tokens/color.js";
import { motion } from "../packages/ui/src/tokens/motion.js";
import { radius } from "../packages/ui/src/tokens/radius.js";
import { shadow } from "../packages/ui/src/tokens/shadow.js";
import { spacing } from "../packages/ui/src/tokens/spacing.js";
import { fontFamily, typography } from "../packages/ui/src/tokens/typography.js";
import { zIndex } from "../packages/ui/src/tokens/zIndex.js";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const stylesDir = path.join(rootDir, "packages", "ui", "src", "styles");

const HEADER = `/*
 * GENERATED by scripts/build-tokens.ts — 수동 편집 금지.
 * 소스는 packages/ui/src/tokens/*.ts 뿐이다. 수정 후 \`pnpm build:tokens\`로 재생성한다.
 */`;

/** CSS 변수명 세그먼트 — `0.5` 같은 키의 `.`은 ident에 쓸 수 없어 `_`로 치환 */
const seg = (key: string) => key.replace(/\./g, "_");

// ── tokens.css ──────────────────────────────────────────────────────────────

const lightVars: string[] = [];
const darkVars: string[] = [];

for (const [group, names] of Object.entries(semanticColor)) {
  for (const [name, themed] of Object.entries<ThemedColor>(names)) {
    lightVars.push(`  --ui-color-${seg(group)}-${seg(name)}: ${themed.light};`);
    darkVars.push(`  --ui-color-${seg(group)}-${seg(name)}: ${themed.dark};`);
  }
}

const staticVars: string[] = [];

for (const [name, value] of Object.entries(fontFamily)) {
  staticVars.push(`  --ui-font-${seg(name)}: ${value};`);
}
for (const [variant, style] of Object.entries(typography)) {
  staticVars.push(`  --ui-text-${seg(variant)}-size: ${style.fontSize};`);
  staticVars.push(`  --ui-text-${seg(variant)}-line-height: ${style.lineHeight};`);
  staticVars.push(`  --ui-text-${seg(variant)}-weight: ${style.fontWeight};`);
}
for (const [key, value] of Object.entries(spacing)) {
  staticVars.push(`  --ui-spacing-${seg(key)}: ${value};`);
}
for (const [key, value] of Object.entries(radius)) {
  staticVars.push(`  --ui-radius-${seg(key)}: ${value};`);
}
for (const [key, value] of Object.entries(shadow)) {
  staticVars.push(`  --ui-shadow-${seg(key)}: ${value};`);
}
for (const [key, value] of Object.entries(motion.duration)) {
  staticVars.push(`  --ui-duration-${seg(key)}: ${value};`);
}
for (const [key, value] of Object.entries(motion.easing)) {
  staticVars.push(`  --ui-easing-${seg(key)}: ${value};`);
}
for (const [key, value] of Object.entries(zIndex)) {
  staticVars.push(`  --ui-z-${seg(key)}: ${String(value)};`);
}

const tokensCss = `${HEADER}

@layer ui.tokens {
  :root {
${[...lightVars, ...staticVars].join("\n").replace(/^ {2}/gm, "    ")}
  }

  /* 다크 테마 — semantic 컬러 변수만 재정의한다. primitive·비컬러 토큰은 테마 불변. */
  [data-theme="dark"] {
${darkVars.join("\n").replace(/^ {2}/gm, "    ")}
  }
}
`;

// ── tailwind-preset.css (Tailwind v4 @theme) ────────────────────────────────
// semantic 네임만 노출한다 — red/green/orange 같은 기본 팔레트 키를 덮으면
// 소비 앱의 bg-red-500이 전멸한다 (리뷰 C5).
// spacing은 매핑하지 않는다 — v4 기본 --spacing: 0.25rem이 이미 4px 그리드다.

const presetVars: string[] = [];

for (const [group, names] of Object.entries(semanticColor)) {
  for (const name of Object.keys(names)) {
    presetVars.push(
      `  --color-${seg(group)}-${seg(name)}: var(--ui-color-${seg(group)}-${seg(name)});`,
    );
  }
}
for (const name of Object.keys(fontFamily)) {
  presetVars.push(`  --font-${seg(name)}: var(--ui-font-${seg(name)});`);
}
for (const variant of Object.keys(typography)) {
  presetVars.push(`  --text-${seg(variant)}: var(--ui-text-${seg(variant)}-size);`);
  presetVars.push(
    `  --text-${seg(variant)}--line-height: var(--ui-text-${seg(variant)}-line-height);`,
  );
  presetVars.push(`  --text-${seg(variant)}--font-weight: var(--ui-text-${seg(variant)}-weight);`);
}
for (const key of Object.keys(radius)) {
  presetVars.push(`  --radius-${seg(key)}: var(--ui-radius-${seg(key)});`);
}
for (const key of Object.keys(shadow)) {
  presetVars.push(`  --shadow-${seg(key)}: var(--ui-shadow-${seg(key)});`);
}
for (const key of Object.keys(motion.duration)) {
  presetVars.push(`  --duration-${seg(key)}: var(--ui-duration-${seg(key)});`);
}
for (const key of Object.keys(motion.easing)) {
  presetVars.push(`  --ease-${seg(key)}: var(--ui-easing-${seg(key)});`);
}

const presetCss = `${HEADER}

/*
 * Tailwind v4 소비자용 선택 preset — 없어도 컴포넌트는 완전 동작한다.
 * var(--ui-*)를 참조하므로 반드시 styles.css를 먼저 import 해야 한다:
 *
 *   @import "@jeon-ji/common-ui/styles.css";
 *   @import "@jeon-ji/common-ui/tailwind-preset.css";
 */
@theme {
${presetVars.join("\n")}
}
`;

writeFileSync(path.join(stylesDir, "tokens.css"), tokensCss);
writeFileSync(path.join(stylesDir, "tailwind-preset.css"), presetCss);

console.error(
  `✔ 토큰 생성 완료 — semantic ${String(lightVars.length)}개, 정적 ${String(staticVars.length)}개, preset ${String(presetVars.length)}개`,
);
